# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Uknj
tagline:          'Thoughts, observations and more.'
description:      'A blog detailing my thoughts, ideas and life in general. Made by <a href="https://twitter.com/theuknj" target="_blank">@theuknj</a>.'
url:              http://github.com/uknj
baseurl:          /

author:
  name:           'Umar Khan'
  url:            https://twitter.com/theuknj

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/uknj
