# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Uknj.github.io
tagline:             'Thoughts, observations and more...'
description:         'A blog written by @theuknj talking about technology, gaming and other miscellaneous things which come to mind'
url:                 http://uknj.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Umar Khan
  url:               https://twitter.com/theuknj
  email:             uknj1995@gmail.com

# Custom vars
version:             1.0.0

# Gem Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

jekyll-mentions:
  base_url: https://twitter.com
